# A sample Gemfile
source "https://rubygems.org"

# gem 'rake'
# gem 'rb-fsevent' #, '~> 0.9.1'
# gem 'guard'
# gem 'guard-test'
# gem 'pry'
# gem 'motion-redgreen'

group :RubyMotion do
  gem 'sugarcube', :github => "rubymotion/sugarcube"
  gem 'ib', :github => "yury/ib"
  gem 'bubble-wrap', :github => "rubymotion/BubbleWrap", :require => "bubble-wrap/all"
  gem 'cocoapods' #, :github => "CocoaPods/CocoaPods"
  gem 'motion-cocoapods' #, :github => "HipByte/motion-cocoapods"
end