# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'
require 'rubygems'
require 'bundler'
Bundler.require(:RubyMotion)

Motion::Project::App.setup do |app|
  app.name = 'GlobalChat2 iOS'
  app.device_family = :iphone
  app.interface_orientations = [:landscape_right]
  app.identifier = 'gc2-ios'
  app.info_plist['UIMainStoryboardFile'] = 'GC2-ios'
  #app.info_plist['UIApplicationExitsOnSuspend'] = true
  #app.provisioning_profile = "/Users/jsilverman2/Library/MobileDevice/Provisioning Profiles/60F7EEB6-6E11-4713-9039-839CDBB930D4.mobileprovision"
  #app.codesign_certificate = "iPhone Distribution: Jonathan Silverman"
  app.icons = ['icon_iphone.png', 'icon_ipad.png', 'icon_iphone_retina.png', 'icon_ipad.png']
  app.prerendered_icon = true
  app.pods do
    pod 'CocoaAsyncSocket'
  end
end
