# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'
require 'rubygems'
require 'bundler'
Bundler.require(:RubyMotion)

Motion::Project::App.setup do |app|
  app.name = 'GlobalChat2 iOS'
  app.device_family = :iphone
  app.interface_orientations = [:landscape_right]
  app.identifier = 'com.jonsoft.globalchat2'
  app.info_plist['UIMainStoryboardFile'] = 'GC2-ios'
  # app.info_plist['UIApplicationExitsOnSuspend'] = true
  app.pods do
    pod 'CocoaAsyncSocket'
  end
end
